## File for reading the input distributions generated by the ARIMA model

# TODO generalize how data is read
# TODO add rainy season data
if sims == 10
    ## 10 simulations TODO update these
    # load_CovMatrix = XLSX.readdata("$dir/CovMat/Data_10Simulations/D_covresmatrix10sim.xlsx", "D_covresmatrix10sim_two", "A2:X$(lpad(length(T)+outage+1, length(digits(Int(length(T)+outage+1)))))") 
    # drySun_CovMatrix = XLSX.readdata("$dir/CovMat/Data_10Simulations/S_covmatrix_dryseason10.xlsx", "S_covmatrix_dryseason10", "A2:X$(lpad(length(T)+outage+1, length(digits(Int(length(T)+outage+1)))))") 
    # rainySun_CovMatrix = XLSX.readdata("$dir/CovMat/Data_10simulations/S_covmatrix_rainyseason10.xlsx", "S_covmatrix_rainyseason10", "A2:X$(lpad(length(T)+outage+1, length(digits(Int(length(T)+outage+1)))))") 

    d = XLSX.readdata("$dir/CovMat/Data_10Simulations/D_forecast10sims.xlsx", "D_forecast10sims_two", "A2:M$(lpad(length(T)+outage+1, length(digits(Int(length(T)+outage+1)))))")
    s_dry = XLSX.readdata("$dir/CovMat/Data_10Simulations/S_dry_forecast10.xlsx", "S_dry_forecast10", "A2:M$(lpad(length(T)+outage+1, length(digits(Int(length(T)+outage+1)))))")
    # s_rainy = XLSX.readdata("$dir/CovMat/Data_10Simulations/S_rainy_forecast10.xlsx", "S_rainy_forecast10", "A2:M$(lpad(length(T)+outage+1, length(digits(Int(length(T)+outage+1)))))")

    d_error = transpose(XLSX.readdata("$dir/CovMat/Data_10Simulations/D_delta10sims.xlsx", "D_delta10sims_two", "A2:X11")) # TODO update this
    s_dry_error = XLSX.readdata("$dir/CovMat/Data_10Simulations/S_dry_error_xi10.xlsx", "S_dry_error_xi10", "A2:J$(lpad(length(T)+outage+1, length(digits(Int(length(T)+outage+1)))))")
    # s_rainy_error = XLSX.readdata("$dir/CovMat/Data_10Simulations/S_rainy_error_xi10.xlsx", "S_rainy_error_xi10", "A2:J$(lpad(length(T)+outage+1, length(digits(Int(length(T)+outage+1)))))")

else
    ## 100 simulations
    # load_CovMatrix = XLSX.readdata("$dir/CovMat/Data_100Simulations/D_covresmatrix100sim_two.xlsx", "D_covresmatrix100sim_two", "A2:X$(lpad(length(T)+outage+1, length(digits(Int(length(T)+outage+1)))))") 
    # drySun_CovMatrix = XLSX.readdata("$dir/CovMat/Data_100Simulations/S_covmatrix_dryseason100.xlsx", "S_covmatrix_dryseason100", "A2:X$(lpad(length(T)+outage+1, length(digits(Int(length(T)+outage+1)))))")
    # rainySun_CovMatrix = XLSX.readdata("$dir/CovMat/Data_100Simulations/S_covmatrix_rainyseason100.xlsx", "S_covmatrix_rainyseason100", "A2:X$(lpad(length(T)+outage+1, length(digits(Int(length(T)+outage+1)))))")

    d = XLSX.readdata("$dir/CovMat/Data_100Simulations/D_forecast100sims_two.xlsx", "D_forecast100sims_two", "A2:CY$(lpad(length(T)+outage+1, length(digits(Int(length(T)+outage+1)))))")
    s_dry = XLSX.readdata("$dir/CovMat/Data_100Simulations/S_dry_forecast100.xlsx", "S_dry_forecast100", "A2:CY$(lpad(length(T)+outage+1, length(digits(Int(length(T)+outage+1)))))")
    # s_rainy = XLSX.readdata("$dir/CovMat/Data_100Simulations/S_rainy_forecast100.xlsx", "S_rainy_forecast100", "A2:CY$(lpad(length(T)+outage+1, length(digits(Int(length(T)+outage+1)))))")

    d_error = transpose(XLSX.readdata("$dir/CovMat/Data_100Simulations/D_delta100sims_two.xlsx", "D_delta100sims_two", "A2:AY101")) # TODO generalize AA instead of selection in line 37 for d_error
    s_dry_error = XLSX.readdata("$dir/CovMat/Data_100Simulations/S_dry_error_xi100.xlsx", "S_dry_error_xi100", "A2:CV$(lpad(length(T)+outage+1, length(digits(Int(length(T)+outage+1)))))")
    # s_rainy_error = XLSX.readdata("$dir/CovMat/Data_100Simulations/S_rainy_error_xi100.xlsx", "S_rainy_error_xi100", "A2:CV$(lpad(length(T)+outage+1, length(digits(Int(length(T)+outage+1)))))")
end
load_mean = [mean(d_error[:,i]) for i in 1:length(T)+outage]
drySun_mean = [mean(s_dry_error[:,i]) for i in 1:length(T)+outage]

# Errors are identically and independently distributed:
CovMatrix = cov(transpose(s_dry_error)) + cov(transpose(d_error[1:length(T)+outage,:]))
Mean =  load_mean + drySun_mean

# μ = load_mean + drySun_mean 
μ = vec([0 for i in 1:length(T)+outage])
Σ = CovMatrix
σ = diag(Σ, 0).^0.5

# Error function for the individual case (defined with the variance)
ξ = []
for i in 1:length(T)+outage
	append!(ξ, [Normal(μ[i], σ[i])])
end

a = vec([-Inf for i in 1:length(T)+outage])
